project:
  type: website
  output-dir: docs              # ← para GitHub Pages (opcional)
  resources:
    - misc/**                   # garanta que a logo e imagens entrem no build
    - data/**

website:
  title: "Ensino em Bioinformática"
  site-url: https://heronoh.github.io/bioinfo/
  search: true
  navbar:
    logo: misc/HOH-02.png
    title: true
    left:
      - text: "Aulas (R)"
        href: aulas/r/index.qmd
      - text: "Aulas (Shell)"
        href: aulas/bash/index.qmd

format:
  html:
    theme: cosmo
    toc: false
    code-copy: true
    smooth-scroll: true
    anchor-sections: false
    # deixe false aqui; use embed-resources: true só quando precisar 1 arquivo solto
    # embed-resources: true
execute:
  freeze: auto                  # builds reprodutíveis e mais rápidos (cache)
