project:
  type: website
  output-dir: docs              # ← para GitHub Pages (opcional)
  resources:
    - misc/**                   # garanta que a logo e imagens entrem no build
    - data/**
lang: pt-BR
date: last-modified
website:
  title: "Bioinformática"
  site-url: https://heronoh.github.io/bioinfo/
  search: true
  navbar:
    logo: misc/HOH-02.png
    left:
      - text: "Aulas (R)"
        href: aulas/r/index.qmd
      - text: "Aulas (bash)"
        href: aulas/bash/index.qmd
      - text: "eDNA scripts"
        href: eDNA/scripts/*.Rmd
      - text: "BLASTr package"
        href: "https://heronoh.github.io/BLASTr/"
      - text: "Extras"
        href: "https://raw.githubusercontent.com/heronoh/bioinfo/main/extras/HeronOH--Simposio_mitocondria_PUC2026.pdf"
      - text: "Sobre mim"
        href: author/author.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    toc: true
    toc-depth: 3
    code-copy: true
    allow-html: true
    embed-resources: true
    smooth-scroll: true
    anchor-sections: false
    # deixe false aqui; use embed-resources: true só quando precisar 1 arquivo solto
    # embed-resources: true
execute:
  freeze: auto                  # builds reprodutíveis e mais rápidos (cache)
editor: source
editor_options:
  chunk_output_type: console
