---
title: "Análises de Heron Hilário"
author: "Heron O.H."
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmdformats::downcute:
    self_contained: true
    toc_float: no
    highlight: zenburn
    code_download: yes
editor_options: 
  chunk_output_type: inline
---

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri("misc/HOH-02.png"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px; width:100px; height:100px')
```



### **Bem vind\∞! **

#### **Esta é uma página dedicada à publicação de materiais didáticos e análises de bioinfo, utilizando _bash_ e _R_,  realizadas por mim. Todos os códigos aqui disponibilizados são de livre reprodução, mas peço gentilmente que referenciem este site ou os artigos publicados relativos a cada um dos _scripts_.**

```{r echo=FALSE, message=TRUE, warning=TRUE, paged.print=FALSE, results='asis'}
cat("</ul>")
cat("<li><a href='eDNA/index.html'><b><i>scripts</i> de <i>eDNA metabarcoding</i></b></a><br/><Cite><i>scripts</i> bioinformáticos em <i>Rmd<i/> para análises de <b>eDNA metabarcoding</b> desenvolvidos por nosso grupo de pesquisa para estudos de detecção e monitoramento de vertebrados e invertebrados.</Cite></li>")
cat("</ul>")

cat("</ul>")
cat("<li><a href='aulas/index.html'><b>Aulas práticas de Bioinformática</b></a><br/><Cite>Conteúdo destinado a iniciantes que querem dar os primeiros passos na interface de linha de comando <b>Linux</b> na utilização de programas e scripts bioinformáticos, e também na linguagem <b>R</b>.</Cite></li>")
cat("</ul>")

```

