---
title: "Pratica_1-Bioinfo"
author: "Heron O. Hilário"
date: 01/2023
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Práticas em Linha de comando - Linux

## Prática I - Navegando em diretórios 

Para se trabalhar na linha de comando, é muito importante saber onde se está. O computador é organizado em diretórios (também chamados de pastas). Todos os diretórios estão contidos dentro de um diretório principal, o *diretório raiz*, representado por */*. Todos os arquivos ou pastas do computador tem uma localização definida, e portanto tem _endereços_. Para a execução de qualquer comando que atua sobre um arquivo é nee que deve ser usada preferencialmente para se evitar a ocorrencia de erros.

cessário se fornecer o endereço deste arquivo.
Há muitas maneiras de se fornecer o endereço de arquivos ou pastas. Vamos começar com a mais completa, 
Este é o primeiro caracter que aparece nos endereços de cada arquivo


```{bash, echo=TRUE,eval=FALSE}


summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{bash, echo=TRUE,eval=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
