---
title: "eDNA metabarcoding analyses"
author: "Heron O.H."
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmdformats::downcute:
    self_contained: true
    toc_float: no
    highlight: zenburn
    code_download: yes
editor_options: 
  chunk_output_type: inline
---

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri("../misc/HOH-02.png"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px; width:100px; height:100px')
```


**Hi there**

**Here you can find the scripts I use to perform eDNA metabarcoding analyses**

Feel free to use and modify the codes below and adapt it to your own analyses, and get in touch if you have any doubts!

### _*pipelines*_
#### R scripts

```{r echo=FALSE, message=TRUE, warning=TRUE, paged.print=FALSE, results='asis'}

rmd <- Sys.glob("scripts/*.Rmd")
# rmd <- Sys.glob("*.Rmd")
rmd <- rmd[rmd != "index_eDNA.Rmd"]
html <- sub(".Rmd", ".html", rmd)
lines <- lapply(rmd, readLines)
yaml <- lapply(lines, rmarkdown:::parse_yaml_front_matter)
cat("<ul>")
for (i in seq_along(rmd)) {
  cat(paste0("<li><a href='", html[i], "'>", yaml[[i]]$title, "</a><br/>",
             "<code>", rmd[i], "</code>", "</li>"))
}
cat("</ul>")
```

