---
title: "Práticas em Bioinformática"
author: "Prof. Heron OH"
place: "Biomedicina - PUC Minas"
date: 01/2023
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: darkly
    highlight: zenburn
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



\_\_<span style="color:darkgreen">Bioinformática para Biomedicina - 2023</span>\_\_


## Práticas em Linha de comando - Linux

### Prática I - Navegando em diretórios 

Para se trabalhar na linha de comando, é muito importante saber onde se está. O computador é organizado em diretórios (também chamados de pastas). Todos os diretórios estão contidos dentro de um diretório principal, o **diretório raiz**, representado pelo símbolo _barra_ (**/**). Todos os arquivos ou pastas do computador tem uma localização definida, e portanto, tem _endereços_. Para a execução de qualquer comando que atua sobre um arquivo deve ser fornecido o seu _endereço_. Para se evitar a ocorrencia de erros usamos, preferencialmente, **_endereços completos_**, ou seja, contendo todas as pastas a partir do diretório raiz, o **/** . Por exemplo:

> Na sua linha de comando ( _bash_ ), escreva o seguinte comando e aperte ***ENTER***.

```{bash, echo=TRUE,eval=FALSE}


summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{bash, echo=TRUE,eval=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
